### ISSUE TITLE
Retropath of dopamine

### ISSUE THREAD

**Issue by Tryhood** [brsynth/rp2paths#1]
Hello! I installed Retropath2.0 and ran successfully the tutorial files. Afterwards I did a trial with dopamine as the source file, ecoli-iJO1366-mnx-compounds as the sink file and knime-ready-rules_mnx-all-reverse_ECOLI-iJO1366 as the rule file (like described in the tutorial pdf).
Poorly the outcome was just a result (56kb) and a source-in-sink file (no scope, no svg)
Pathlength was set to 5. What could be the problem?

Thanks in advance!

**Comment by tduigou** [comment]
For information: from amongst all the chemical reactions generated using RetroPath2.0 (in the retrosynthetic way), only a subset may effectively link a source to a subset of sink compounds. This sub-network is considered as a scope and is output in dedicated files (see below). Scope and SVG files are outputted only when such scope if found.
