### ISSUE TITLE
Scope Task: no scope matrix was produced, exit

### ISSUE THREAD

**Issue by Melclic** [brsynth/rp2paths#3]
The following input file, [rp_pathways_74.zip](https://github.com/brsynth/rp2paths/files/4980837/rp_pathways_74.zip) returns the following message:
`Scope Task: no scope matrix was produced, exit`

Note that these are partial results returned by RetroPath2.0. Using the following conditions (the rest are default):

**Molecule Name:** Resokaempferol
**Molecule InChI:** InChI=1S/C15H10O5/c16-9-3-1-8(2-4-9)15-14(19)13(18)11-6-5-10(17)7-12(11)20-15/h1-7,16-17,19H/p-1
**GEM SBML:** e_coli_iML1515.sbml
**TopX:** 1000
**Max Steps:** 6
**Rule Diameters:** 2,4,6,8,10,12,14,16

**Comment by tduigou** [comment]
I get the same output message on my installation. Some explanation that could if someone else get the message: such message is raised when not any subnetwork is found that fullfills all precursors requirements. In such situation, one needs to try generate new results with RetroPath2.0 with different settings (such a lower max diameter, different set of reaction rules or of sink compounds, increase the number of steps, increase the topX parameter, ...).
